### ISSUE TITLE
When will the datasets and models be released?

### ISSUE THREAD

**Issue by GokulNC** [Jivnesh/EvalSan#1]
Hello!

I came across your paper ["Evaluating Neural Word Embeddings for Sanskrit"](https://arxiv.org/abs/2104.00270) and found it quite interesting & useful.

May I know when will the resources for the same be released as mentioned in the work?
Thanks!

**Comment by Jivnesh** [comment]
Happy to see your interest in our work. I will try to make this available in the next 10-15 days. Actually, I am busy with one submission, and the codes need some cleanup. I hope you are ok with this.

**Comment by GokulNC** [comment]
Thanks, no problem!

**Comment by Jivnesh** [comment]
Hi @GokulNC The datasets, evaluation codes and the pretrained models are available now. Sorry, for the delay.
